# Generated by Django 5.1.2 on 2024-10-19 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sondage',
            name='question',
        ),
        migrations.AddField(
            model_name='reponse',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, 'Masculin'), (2, 'Feminin')], null=True),
        ),
        migrations.AddField(
            model_name='sondage',
            name='active_sex_option',
            field=models.BooleanField(default=0),
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sondage_categorie', to='analyse.sondage')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie_option',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=200)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie_option', to='analyse.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sondage_question', to='analyse.sondage')),
            ],
        ),
        migrations.AlterField(
            model_name='reponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='analyse.question'),
        ),
        migrations.CreateModel(
            name='Tranche_age',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('debut', models.IntegerField()),
                ('fin', models.IntegerField()),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranche_age', to='analyse.sondage')),
            ],
        ),
        migrations.AddField(
            model_name='reponse',
            name='tranche_age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='analyse.tranche_age'),
        ),
    ]
